CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    pin_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    profile_photo VARCHAR(255),
    identity_number VARCHAR(50),
    identity_type ENUM('KTP', 'PASSPORT', 'SIM') DEFAULT 'KTP',
    identity_verified BOOLEAN DEFAULT FALSE,
    user_type ENUM('RETAIL', 'RESELLER', 'MASTER', 'ADMIN') DEFAULT 'RETAIL',
    status ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'BANNED') DEFAULT 'INACTIVE',
    kyc_status ENUM('PENDING', 'VERIFIED', 'REJECTED') DEFAULT 'PENDING',
    kyc_rejection_reason TEXT,
    two_factor_enabled BOOLEAN DEFAULT FALSE,
    two_factor_method ENUM('OTP', 'SMS', 'EMAIL') DEFAULT 'OTP',
    last_login_at TIMESTAMP NULL,
    last_login_ip VARCHAR(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    INDEX (username),
    INDEX (email),
    INDEX (phone),
    INDEX (user_type),
    INDEX (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;